redis:
  host: "localhost"
  port: "6379"
  password: ""
  indices: "0-5"
  key_prefix: "" #can be empty
  timeout: 5

server:
  host: "localhost"
  port: "8080"
  mode: "test" # can be "release", "debug" or "test". default is "release"

config:
  hash_keys: true

