services:
  otp-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: otp-service
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Tehran
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - otp-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  redis:
    image: redis:7.2-alpine
    container_name: otp-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    networks:
      - otp-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  otp-network:
    driver: bridge
