# docker-compose.yaml for OTP Service

services:
  otp-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_KEY_PREFIX=
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - HASH_KEYS=true
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
