services:
  otp-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: otp-service
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=otp-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0-5
      - REDIS_KEY_PREFIX=otp
      - REDIS_TIMEOUT=5
      - REDIS_HASH_KEYS=true
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - SERVER_MODE=debug
      - SERVER_TIMEOUT_READ=5
      - SERVER_TIMEOUT_WRITE=10
      - SERVER_TIMEOUT_IDLE=120
      - SERVER_TIMEOUT_READ_HEADER=2
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - otp-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  redis:
    image: redis:alpine
    container_name: otp-redis
    command: redis-server --appendonly yes
    ports:
      - "6380:6379"
    # volumes:
    #   - redis-data:/data
    networks:
      - otp-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  otp-network:
    driver: bridge

# volumes:
#   redis-data:
#     driver: local