version: '3.8'

services:
  otp_service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - GIN_MODE=release
    volumes:
      - ./config.yaml:/root/config.yaml
      - ./i18n:/root/i18n

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
