redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: "0"
  key_prefix: "" #can be empty
  timeout: 5
  hash_keys: true

server:
  host: "localhost"
  port: "8080"
  mode: "debug" # can be "release" or "debug". default is "release"
  timeout:
    read: 5
    write: 10
    idle: 120
    read_header: 2
  tls: 
    enabled: false
    cert_file: "cert.pem"
    key_file: "key.pem"
    client_certs: "client_certs.pem"

